name: Scrape USD & Gold Prices

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5min
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'scraper/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./scraper
        run: npm install
        
      - name: Run Scraper
        working-directory: ./scraper
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node scraper.js
        
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scraper/data.json
          git commit -m "Auto-update scraped data [skip ci]" || echo "No changes to commit"
          git push
